env:
  es2021: true
  node: true
extends:
  - '@react-native-community'
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
rules: {
  'prettier/prettier': error,
  'react/react-in-jsx-scope': off
}
